name: iris_notifier
version: 0.0.5
description: A package for notifier. This package includes several notifiers. Notify for data, Notify for event and Notify for state.

repository: https://github.com/ali-1989/irisNotifier


environment:
  sdk: '>=3.0.0 <4.0.0'


dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.1



# dart pub publish
